// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-r1H1OLYIZLXoMhhYkM8PMTwS9Gx9RSg',
    appId: '1:35619403250:web:2056acd081c18a0542276b',
    messagingSenderId: '35619403250',
    projectId: 'blossom-kids-f69fb',
    authDomain: 'blossom-kids-f69fb.firebaseapp.com',
    databaseURL: 'https://blossom-kids-f69fb-default-rtdb.firebaseio.com',
    storageBucket: 'blossom-kids-f69fb.firebasestorage.app',
    measurementId: 'G-BY2XVQK632',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGolW7MccIFn6jL4vt_qwWOIP7rwsdHU',
    appId: '1:35619403250:android:a2c526de46357dee42276b',
    messagingSenderId: '35619403250',
    projectId: 'blossom-kids-f69fb',
    databaseURL: 'https://blossom-kids-f69fb-default-rtdb.firebaseio.com',
    storageBucket: 'blossom-kids-f69fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Bmh6dCqs3QT3Zxhc3Vz1SUVw4Our12s',
    appId: '1:35619403250:ios:887b9d3af0afc17b42276b',
    messagingSenderId: '35619403250',
    projectId: 'blossom-kids-f69fb',
    databaseURL: 'https://blossom-kids-f69fb-default-rtdb.firebaseio.com',
    storageBucket: 'blossom-kids-f69fb.firebasestorage.app',
    iosClientId: '35619403250-5v6btgmi88sm9isnmh268hq2d6ame3v6.apps.googleusercontent.com',
    iosBundleId: 'com.example.blossomsKids',
  );
}
